apiVersion: v1
kind: Pod
metadata:
  name: test-secret2 
spec:
  containers:
  - name: test-secret-var
    image: busybox
    args:
    - sleep
    - "86400"
    env:
      - name: SECRET_DB_PASS
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: db-pass
