apiVersion: v1
kind: Pod
metadata:
  name: test-cm2
spec:
  containers:
  - name: test-cm-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: owner-name
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: owner-name
    projected:
      sources:
      - configMap:
          name: test-cm

