apiVersion: v1
kind: Pod
metadata:
  name: test-secret1
spec:
  containers:
  - name: test-secret-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: db-pass
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: db-pass
    projected:
      sources:
      - secret:
          name: test-secret

