apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31111

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx-deploy
spec:
  replicas: 3
  template:
    metadata:
        labels:
            app: my-nginx
    spec:
        volumes:
         - name: html-volume
           emptyDir: {}
        initContainers:
          - name: init-html
            image: busybox
            command:
             - /bin/sh
             - "-c" 
             - |
               echo "$(hostname)" > /tmp/index.html
               touch /tmp/liveness
               touch /tmp/readiness
            volumeMounts:
             - mountPath: /tmp
               name: html-volume
        containers:
         - name: test-http
           image: nginx:alpine
           volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html-volume
           livenessProbe:
             httpGet:
                    path: /liveness
                    port: 80
             initialDelaySeconds: 5
             periodSeconds: 10
           readinessProbe:
             httpGet:
                    path: /readiness
                    port: 80
             initialDelaySeconds: 5
             periodSeconds: 6

